[package]
name = "lrp"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
prettytable-rs = "0.10.0"

[[bench]]
name = "benchmarks"
harness = false

[dev-dependencies]
hermes_bench = "0.1.0"

[workspace]
members = ["wop"]
